# Generated by Django 2.0.6 on 2018-06-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Infos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('type', models.TextField()),
                ('data', models.TextField()),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
