# Generated by Django 2.0.6 on 2018-07-09 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0002_auto_20180620_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encoding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('value', models.TextField()),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.RemoveField(
            model_name='picture',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='firstname',
            field=models.TextField(default='undefined', max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
        migrations.AddField(
            model_name='encoding',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memory.User'),
        ),
    ]
