# Generated by Django 2.0.6 on 2018-07-09 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0003_auto_20180709_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encoding',
            old_name='user_id',
            new_name='user',
        ),
    ]
