#!/usr/bin/env sh
SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
if [ -f ${SCRIPTPATH}/../.env ]; then
    . ${SCRIPTPATH}/../.env
fi
echo ${SCRIPTPATH}/../.env
curl --user ${REMOTE_DATA_LOGIN}:${REMOTE_DATA_PASSWD} https://files.api.suricats-consulting.com/credentials/memory/.env -o ${SCRIPTPATH}/../.env
