#!/usr/bin/env sh

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
echo "$( cd "${SCRIPTPATH}/../" ; pwd -P )"
if [ -f ${SCRIPTPATH}/../.env ]; then
    . ${SCRIPTPATH}/../.env
fi
echo ${SCRIPTPATH}/../.env
mkdir -p ${SCRIPTPATH}/../res/credentials
curl --user ${REMOTE_DATA_LOGIN}:${REMOTE_DATA_PASSWD} https://files.api.suricats-consulting.com/credentials/memory/google.json -o ${SCRIPTPATH}/../res/credentials/google.json
curl --user ${REMOTE_DATA_LOGIN}:${REMOTE_DATA_PASSWD} https://files.api.suricats-consulting.com/credentials/memory/token.json -o ${SCRIPTPATH}/../res/credentials/token.json
